#!/bin/bash
#
# $Id: slurm_cpus_partitions 3832 2022-11-14 09:42:26Z ltaulell $

: << =cut

=head1 NAME

slurm_cpus - Plugin to measure the number of cpus by partition in SLURM queue.

=head1 NOTES

Shows the number of CPUs in use by slurm queued jobs.

=head1 AUTHOR

Contributed by Rael Garcia Arnes (raelga@gmail.com)
Modified for PSMN by Loïs Taulelle (ltaulell@psmn.ens-lyon)

=head1 LICENSE

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this program.  If not, see <http://www.gnu.org/licenses/>.

=head1 MAGIC MARKERS

#%# family=auto
#%# capabilities=autoconf

=cut

# . $MUNIN_LIBDIR/plugins/plugin.sh

case $1 in
    autoconf)
        echo yes 
        exit 0
        ;;

    config)
        echo graph_title "CPUs by slurm partitions"
        echo graph_vlabel "CPUs"
        echo graph_category Slurm
        echo graph_args "--base 1000 -l 0 --lower-limit 0"

        for i in $(sinfo -h -o "%R")
        do
            echo slurm_cpus_run_"${i}".label "${i} CPUs running"
            echo slurm_cpus_wait_"${i}".label "${i} CPUs pending"
        done

        exit 0
        ;;
esac


#squeue_out=$(squeue -h -o "%t %C")
#echo "$squeue_out" | awk 'BEGIN {s=0} /R/ {s+=$2} END {printf "slurm_cpus_run.value  %g\n", s}'
for i in $(sinfo -h -o "%R")
do
    echo -n "slurm_cpus_run_${i}.value "
    squeue -h -p "${i}" -o "%t %C" | awk 'BEGIN {s=0} /R/ {s+=($2)} END {printf "%g\n", s}'
done

#echo "$squeue_out" | awk 'BEGIN {s=0} /PD/ {s+=$2} END {printf "slurm_cpus_wait.value  %g\n", s}'
for i in $(sinfo -h -o "%R")
do
    echo -n "slurm_cpus_wait_${i}.value "
    squeue -h -p "${i}" -o "%t %C" | awk 'BEGIN {s=0} /PD/ {s+=$2} END {printf "%g\n", s}'
done
