#!/bin/bash
#
# $Id: slurm_jobs_partitions_simplified 3832 2022-11-14 09:42:26Z ltaulell $

: << =cut

=head1 NAME

slurm_jobs - Plugin to measure the number of jobs by partitions (simplified) in SLURM queue.

=head1 NOTES

Especially the average and max values on the bigger graphs (yearly) can be interesting.

=head1 AUTHOR

Contributed by Rael Garcia Arnes (raelga@gmail.com)
Modified for PSMN by Loïs Taulelle (ltaulell@psmn.ens-lyon)

=head1 LICENSE

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this program.  If not, see <http://www.gnu.org/licenses/>.

=head1 MAGIC MARKERS

#%# family=auto
#%# capabilities=autoconf

=cut

# . $MUNIN_LIBDIR/plugins/plugin.sh

case $1 in
    autoconf)
        echo yes 
        exit 0
        ;;

    config)
        echo graph_title "Jobs by slurm partitions (simplified)"
        echo graph_vlabel "Jobs"
        echo graph_args "--base 1000 -l 0 --lower-limit 0"
        echo graph_category Slurm

        for i in $(sinfo -h -o "%R")
        do
            echo slurm_jobs_pending_"${i}".label "${i} pending"
            echo slurm_jobs_running_"${i}".label "${i} running"
            echo slurm_jobs_other_states_"${i}".label "${i} other states"
        done

        exit 0
        ;;
esac

#squeue_out=$(squeue -h -o "%T")
#echo "$squeue_out" | awk 'BEGIN {c=0} /PENDING/ {c++} END {print "slurm_jobs_pending.value " c}'
for i in $(sinfo -h -o "%R")
do
    echo -n "slurm_jobs_pending_${i}.value " 
    squeue -h -p "${i}" -o "%T" | awk 'BEGIN {c=0} /PENDING/ {c++} END {print c}'
done
#echo "$squeue_out" | awk 'BEGIN {c=0} /RUNNING/ {c++} END {print "slurm_jobs_running.value " c}'
for i in $(sinfo -h -o "%R")
do
    echo -n "slurm_jobs_running_${i}.value " 
    squeue -h -p "${i}" -o "%T" | awk 'BEGIN {c=0} /RUNNING/ {c++} END {print c}'
done
#echo "$squeue_out" | awk 'BEGIN {c=0} /SUSPENDED/ {c++} END {print "slurm_jobs_suspended.value " c}'
for i in $(sinfo -h -o "%R")
do
    echo -n "slurm_jobs_other_states_${i}.value " 
    squeue -h -p "${i}" -o "%T" | awk 'BEGIN {c=0} /SUSPENDED/ || /CANCELLED/ || /COMPLE/ || /CONFIGURING/ || /FAILED/ || /TIMEOUT/ || /NODE_FAIL/ {c++} END {print c}'
done
