#!/bin/bash
# -*- sh -*-
#
# Copyright (C) 2011 PSMN / ENS de Lyon - LT
# $Id: sge_users 2757 2019-12-05 10:13:27Z ltaulell $
#
# Abstract
# Script to monitor SGE work, users activity
#
# Authors
#  . Loïs Taulelle <lois dot taulelle at ens-lyon dot fr>
#
# Parameters understood:
#
# 	config   (required)
# 	autoconf (optional - used by munin-config)
#

if [[ -e "/etc/munin/plugins/sge_common" ]]; then
  source /etc/munin/plugins/sge_common
else
  echo "no common config"
  exit 1
fi

#
# Configuration:
# add /etc/munin/plugin-conf.d/munin-node
# [sge_*]
# user root
#
# Magic markers (optional - used by munin-config and installation
# scripts):
#
#%# family=auto
#%# capabilities=autoconf

#set -x # trace each command

if [ "$1" = "autoconf" ]; then
  if [ -x $(which qstat) ]; then
    echo yes
    exit 0
  else
    echo "no (qstat not found)"
    exit 1
  fi
fi

if [ "$1" = "config" ]; then
  echo "graph_title SGE users activity"
  echo "graph_args --base 1000 -l 0 --lower-limit 0"
  echo "graph_vlabel number of users"
  echo "graph_category sge"
  
  echo "sge_users_run.label Running users"
  echo "sge_users_wait.label Pending users"
#  echo "sge_users_total.draw AREA"
  echo "sge_users_total.label Total"

  exit 0
fi

USERSRUN=$(qstat -u '*' | awk '{print $4,$5}' | sort | uniq | grep -vi -e "qw$" -e "t$" -e "state$" -e "dr$" | wc -l)
echo "sge_users_run.value $USERSRUN"

USERSWAIT=$(qstat -u '*' | awk '{print $4,$5}' | sort | uniq | grep -vi -e "r$" -e "t$" -e "state$" -e "dr$" | wc -l)
echo "sge_users_wait.value $USERSWAIT"

USERSTOTAL=$(qstat -u '*' | awk '{print $4,$5}' | sort | uniq | wc -l)
echo "sge_users_total.value $USERSTOTAL"
