#!/bin/bash
# -*- sh -*-
#
# Copyright (C) 2011 PSMN / ENS de Lyon - LT
# $Id: sge_cpu_active 2757 2019-12-05 10:13:27Z ltaulell $
#
# Abstract
# Script to monitor SGE work, by cpu
#
# Authors
#  . Loïs Taulelle <lois dot taulelle at ens-lyon dot fr>
#
# Parameters understood:
#
# 	config   (required)
# 	autoconf (optional - used by munin-config)
#

if [[ -e "/etc/munin/plugins/sge_common" ]]; then
  source /etc/munin/plugins/sge_common
else
  echo "no common config"
  exit 1
fi

#
# Configuration:
# add /etc/munin/plugin-conf.d/munin-node
# [sge_*]
# user root
#
# Magic markers (optional - used by munin-config and installation
# scripts):
#
#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
  if [ -x $(which qstat) ]; then
    echo yes
    exit 0
  else
    echo "no (qstat not found)"
    exit 1
  fi
fi

if [ "$1" = "config" ]; then
  echo "graph_title SGE total active cores"
  echo "graph_args --base 1000 -l 0 --lower-limit 0"
  echo "graph_vlabel number of cores"
  echo "graph_category sge"

  echo "sge_cpu.draw LINE2"
  echo "sge_cpu.label Active cores"

  exit 0
fi

CPU=$(qstat -g c | grep -vi -e "test" | tail -n +3 | awk '{somme+=$3} END {print somme}')
echo "sge_cpu.value $CPU"

