#!/bin/bash
# -*- sh -*-
#
# Copyright (C) 2011 PSMN / ENS de Lyon - LT
# $Id: sge_activity_run 2177 2018-03-13 12:49:29Z ltaulell $
#
# Abstract
# Script to monitor SGE work, details by jobs
#
# Authors
#  . Loïs Taulelle <lois dot taulelle at ens-lyon dot fr>
#
# Parameters understood:
#
# 	config   (required)
# 	autoconf (optional - used by munin-config)
#
# Environment SGE:

if [[ -e "/etc/munin/plugins/sge_common" ]]; then
  source /etc/munin/plugins/sge_common
else
  echo "no common config"
  exit 1
fi

#
# Configuration:
# add /etc/munin/plugin-conf.d/munin-node
# [sge_*]
# user root
#
# Magic markers (optional - used by munin-config and installation
# scripts):
#
#%# family=auto
#%# capabilities=autoconf

#set -x # trace each command

if [ "$1" = "autoconf" ]; then
  if [ -x $(which qstat) ]; then
    echo yes
    exit 0
  else
    echo "no (qstat not found)"
    exit 1
  fi
fi

if [ "$1" = "config" ]; then
  echo "graph_title SGE activity (running jobs & cores)"
  echo "graph_args --base 1000 -l 0 --lower-limit 0"
  echo "graph_vlabel number of jobs and cores"
  echo "graph_category sge"
  
  echo "sge_jobs_run.label Running jobs"
  echo "sge_jobs_run.draw LINE2"
  echo "sge_cores_run.label Running cores"
  echo "sge_avg.draw AREA"
  echo "sge_avg.label Average cores by jobs"

  exit 0
fi

JOBSRUN=$(qstat -u '*' | awk '{print $4,$5}' | sort | grep -vi -e "qw$" -e "t$" -e "state$" -e "dr$" | wc -l)
echo "sge_jobs_run.value $JOBSRUN"

CORESRUN=$(qstat -g c | grep -vi -e "test" | tail -n +3 | awk '{somme+=$3} END {print somme}')
echo "sge_cores_run.value $CORESRUN"

let "AVG=$CORESRUN / $JOBSRUN"
echo "sge_avg.value $AVG"
