#!/bin/bash
# -*- sh -*-
#
# Copyright (C) 2011 PSMN / ENS de Lyon - LT
# $Id: sge_average 3835 2022-11-14 10:54:56Z ltaulell $
#
# Abstract
# Script to monitor SGE work, by cpu
#
# Authors
#  . Loïs Taulelle <lois dot taulelle at ens-lyon dot fr>
#
# Parameters understood:
#
# 	config   (required)
# 	autoconf (optional - used by munin-config)
#

if [[ -e "/etc/munin/plugins/sge_common" ]]; then
  source /etc/munin/plugins/sge_common
else
  echo "no common config"
  exit 1
fi

#
# Configuration:
# add /etc/munin/plugin-conf.d/munin-node
# [sge_*]
# user root
#
# Magic markers (optional - used by munin-config and installation
# scripts):
#
#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
  if [ -x $(which qstat) ]; then
    echo yes
    exit 0
  else
    echo "no (qstat not found)"
    exit 1
  fi
fi

if [ "$1" = "config" ]; then
  echo "graph_title SGE activity (Average cores by jobs)"
  echo "graph_args --base 1000 -l 0 --lower-limit 0"
  echo "graph_vlabel average cores by jobs"
  echo "graph_category sge"

  echo "sge_wait_avg.label Average cores by pending jobs"
  echo "sge_wait_avg.draw LINE"
  echo "sge_run_avg.label Average cores by running jobs"
  echo "sge_run_avg.draw LINE"

  exit 0
fi

# slots waiting
PENDING=$(qstat -s p -u "*" | awk '{somme+=$8} END {print somme}')
#echo "sge_cores_wait.value $PENDING"

# jobs waiting
JOBSWAIT=$(qstat -u '*' | awk '{print $4,$5}' | sort | grep -vi -e "r$" -e "t$" -e "state$" -e "dr$" | wc -l)
#echo "sge_jobs_wait.value $JOBSWAIT"

#let "AVG=$PENDING / $JOBSWAIT"
AVG=$(echo "scale=2;${PENDING}/${JOBSWAIT}" |bc -l )
echo "sge_wait_avg.value $AVG"

JOBSRUN=$(qstat -u '*' | awk '{print $4,$5}' | sort | grep -vi -e "qw$" -e "t$" -e "state$" -e "dr$" | wc -l)
#echo "sge_jobs_run.value $JOBSRUN"

CORESRUN=$(qstat -g c | grep -vi -e "test" | tail -n +3 | awk '{somme+=$3} END {print somme}')
#echo "sge_cores_run.value $CORESRUN"

#let "AVG=$CORESRUN / $JOBSRUN"
AVG=$(echo "scale=2;${CORESRUN}/${JOBSRUN}" |bc -l )
echo "sge_run_avg.value $AVG"
